const menuList = [
    {
        title: "总览",
        key: '/home'
    },
    {
        title:"租户中心",
        key: "/home/tenant-center"
    },
    {
        title:"个人中心",
        key: "/home/personal-center"
    },
    {
        title:"服务",
        key: "/home/service",
        children:[
            {
                title:"访问API",
                key:"/home/service/access-api"
            },
            {
                title:"配额管理",
                key:"/home/service/quota-management"
            }
        ]
    },
    {
        title:"产品",
        key:"/home/product",
        children:[
            {
                title:"云控制台",
                key:"/home/product/control",
                children:[
                    {
                        title:"计算",
                        key:"/home/calculate",
                        children:[
                            {
                                title:"Node",
                                key:"/home/calculate/node"
                            },
                            {
                                title:"Pod",
                                key:"/home/calculate/pod"
                            },
                            {
                                title:"Kvm",
                                key:"/home/calculate/kvm"
                            },
                            {
                                title:"Deployment",
                                key:"/home/calculate/deployment"
                            }
                        ]
                    },
                    {
                        title:"存储",
                        key:"/home/storage",
                        children:[
                            {
                                title:"ConfigMap",
                                key:"/home/storage/configMap"
                            },
                            {
                                title:"PersistenVolumeClaims",
                                key:"/home/storage/pvc"
                            },
                            {
                                title:"VolumeSnapshot",
                                key:"/home/storage/volumeSnapshot"
                            },
                            {
                                title:"StorageClass",
                                key:"/home/storage/storageClass"
                            }
                        ]
                    },
                    {
                        title:"网络",
                        key:"/home/Internet",
                        children:[
                            {
                                title:"service",
                                key:"/home/Internet/service"
                            },
                            {
                                title:"location",
                                key:"/home/Internet/location"
                            },
                        ]
                    },
                    {
                        title:"K8s集群管理",
                        key:"/home/k8s-manage",
                        children:[
                            {
                                title:"集群管理",
                                key:"/home/k8s-manage/cluster-manage"
                            },
                        ]
                    }
                ]
            }
        ]
    },
];

export default menuList;